apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: potato-facts
  namespace: borealis-argo
  annotations: 
    "app": "potato-facts"
    "prometheus.io/scrape": "true"
spec:
  strategy:
    canary:
      canaryService: potato-facts-external
      steps:
      - setWeight: 100
  revisionHistoryLimit: 0
  replicas: 4
  selector:
    matchLabels:
      app: potato-facts
  template:
    metadata:
      labels:
        app: potato-facts
      annotations:
        "app": "potato-facts"
        "prometheus.io/scrape": "true"
        linkerd.io/inject: enabled
    spec:
      containers:
#      - image:  armory/potato-facts:v1.6.0 #v1.5.1 #v1.6.0 # v1.7.0
      - image:  demoimages/bluegreen:v3 #v5, v4, v3
        imagePullPolicy: Always
        name: potato-facts
        resources:
          limits:
            cpu: "100m" # this is to ensure the above busy wait cannot DOS a low CPU cluster.
            memory: "70Mi"
          requests:
            cpu: "10m" # this is to ensure the above busy wait cannot DOS a low CPU cluster.
            memory: "70Mi"
        env:
        - name: NEW_RELIC_AGENT_ENBALED
          value: 'false'
        ports:
          - containerPort: 8000
      restartPolicy: Always

