apiVersion: apps/v1
kind: Deployment
metadata:
  name: potato-facts
  namespace: borealis
  annotations: 
    "app": "potato-facts"
    "prometheus.io/scrape": "true"
spec:
  revisionHistoryLimit: 1
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: potato-facts
  template:
    metadata:
      labels:
        app: potato-facts
      annotations: 
        "app": "potato-facts"
        "prometheus.io/scrape": "true"
    spec:
      containers:
#      - image:  armory/potato-facts:v1.7.0 #v1.5.1 #v1.6.0 # v1.7.0
      - image:  demoimages/bluegreen:v4 #v5, v4, v3
        imagePullPolicy: Always
        name: potato-facts
        resources:
          limits:
            cpu: "10m" # this is to ensure the above busy wait cannot DOS a low CPU cluster.
        env:
        - name: NEW_RELIC_AGENT_ENBALED
          value: 'false'
        #ports:
        #  - containerPort: 8086
      restartPolicy: Always


#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: potato-facts
#  name: potato-facts
#  namespace: borealis
#spec:
#  ports:
#  - name: gate-tcp
#    port: 80
#    protocol: TCP
#    targetPort: 8086
#  selector:
#    app: potato-facts
#  type: ClusterIP















