apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component #Kustomization


#openapi:
#  path: openapi.json
patches:
  - path: webhook2.yml
    target:
      version: .*
      kind: .*
      name: .*
  - path: strategies.yml
  - path: queries.yml


generatorOptions:
  disableNameSuffixHash: true
