apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: pmm-anna
  namespace: default
  labels:
    type: cdaasDemo
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: pmm-anna-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSManagedCluster
    name: pmm-anna
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: pmm-anna
  namespace: default
  labels:
    type: cdaasDemo
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: pmm-anna-control-plane
  namespace: default
  labels:
    type: cdaasDemo
spec:
  addons:
    - name: vpc-cni
      version: v1.12.2-eksbuild.1
      conflictResolution: overwrite
  region: us-east-1
  sshKeyName: default
  version: v1.25.0
  vpcCni:
    env:
      - name: ENABLE_PREFIX_DELEGATION
        value: "true"
  network:
    vpc:
      enableIPv6: "true"
      ipv6:
        poolId: ipam-pool-0ff093b014e327480
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: pmm-anna-pool-0
  namespace: default
  labels:
    type: cdaasDemo
spec:
  clusterName: pmm-anna
  replicas: 3
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: pmm-anna
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: pmm-anna-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: pmm-anna-pool-0
  namespace: default
  labels:
    type: cdaasDemo
spec:
  availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
