apiVersion: v1
data:
  rna.yml: |
    ---
    # Source: remote-network-agent/templates/service-account.yaml
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: remote-network-agent-service-account
      namespace: armory-rna
      labels:
        helm.sh/chart: remote-network-agent-2.0.2
        app.kubernetes.io/name: "remote-network-agent"
        app.kubernetes.io/instance: armory-rna
        app.kubernetes.io/version: "v3.0.17"
        app.kubernetes.io/managed-by: Helm
    ---
    # Source: remote-network-agent/templates/cluster-role.yaml
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: rna-armory-rna-cr
    rules:
    - apiGroups:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    ---
    # Source: remote-network-agent/templates/cluster-role-binding.yaml
    kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: rna-armory-rna-cr-binding
      labels:
        helm.sh/chart: remote-network-agent-2.0.2
        app.kubernetes.io/name: "remote-network-agent"
        app.kubernetes.io/instance: armory-rna
        app.kubernetes.io/version: "v3.0.17"
        app.kubernetes.io/managed-by: Helm
    subjects:
      - kind: ServiceAccount
        name: remote-network-agent-service-account
        namespace: armory-rna
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: rna-armory-rna-cr
    ---
    # Source: remote-network-agent/templates/deployment.yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: remote-network-agent-deployment
      namespace: armory-rna
      labels:
        helm.sh/chart: remote-network-agent-2.0.2
        app.kubernetes.io/name: "remote-network-agent"
        app.kubernetes.io/instance: armory-rna
        app.kubernetes.io/version: "v3.0.17"
        app.kubernetes.io/managed-by: Helm
    spec:
      replicas: 2
      selector:
        matchLabels:
          app.kubernetes.io/name: "remote-network-agent"
          app.kubernetes.io/instance: armory-rna
      template:
        metadata:
          labels:
            app.kubernetes.io/name: "remote-network-agent"
            app.kubernetes.io/instance: armory-rna
        spec:
          serviceAccountName: remote-network-agent-service-account
          containers:
            - name: remote-network-agent
              image: "armory/remote-network-agent:v3.0.17"
              imagePullPolicy: IfNotPresent
              livenessProbe:
                httpGet:
                  path: /health/liveness
                  port: 8080
              startupProbe:
                periodSeconds: 1
                timeoutSeconds: 1
                successThreshold: 1
                failureThreshold: 60
                httpGet:
                  path: /health/liveness
                  port: 8080
              envFrom:
              -  configMapRef:
                  name: rna-config
                #- name: APPLICATION_NAME
                #  value: "rna"
                #- name: APPLICATION_ENVIRONMENT
                #  value: prod
                #- name: APPLICATION_VERSION
                #  value: "v3.0.17"
                #- name: LOGGER_TYPE
                #  value: "console"
                #- name: LOGGER_LEVEL
                #  value: "info"
                #- name: DISABLE_COLORS
                #  value: "false"
                #- name: oidc_clientId
                #  value: "encrypted:k8s!n:controlplane-client-credentials!k:client-id"
                #- name: oidc_clientSecret
                #  value: "encrypted:k8s!n:controlplane-client-credentials!k:client-secret"
                #- name: agent_identifier
                #  value: "default_satwell-temp-feb-23-2023-control-plane"
                #- name: agent_kubernetesClusterModeEnabled
                #  value: "true"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: rna
