apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::957626022434:role/nodes.cluster-api-provider-aws.sigs.k8s.io
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::957626022434:role/eks-nodegroup.cluster-api-provider-aws.sigs.k8s.io
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::957626022434:role/okta-admin-role
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-14T23:17:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5348"
  uid: 50018e1b-e1aa-420c-a48e-39ea178e3fa5
